[project]
name = "discovery"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "yt-dlp>=2025.1.0",
    "groq>=1.0.0",
    "python-dotenv>=1.2.1",
    "ddgs>=9.10.0",
]
